### ISSUE TITLE
Проблема с авторизацией пользователя Postman POST /auth/token/login/

### ISSUE THREAD

**Issue by BeardyVegas** [social-network-ya-practicum/backend#49]
POST https://csn.sytes.net/auth/token/login/

![Image](https://user-images.githubusercontent.com/134094409/247978299-1f7e9d79-9df9-42b7-9bf4-3c21735bf573.png)
![Image](https://user-images.githubusercontent.com/134094409/247978298-e415cc92-0229-4fb0-9d7a-173de25ef766.png)

При вводе данных для авторизации зарегистрированного пользователя: 
```
{
  "password": "aZxkeapme88",
  "email": "kfofofkskkddjdkdodod@yandex.ru"
}
```
Приходит ответ: 400Bad Request
```
{
    "non_field_errors": [
        "Невозможно войти с предоставленными учетными данными."
    ]
}
```

**Comment by Imwisagist** [comment]
Проблема в синтаксисе, email написан с опечаткой, проблема закрыта
