### ISSUE TITLE
QA БАГ: При редактировании личного профиля нет возможности сохранить изменения при незаполненных полях личной почты и личного телефона

### ISSUE THREAD

**Issue by Veronika-Khitraia** [social-network-ya-practicum/backend#92]
При редактировании профиля пользователя нет возможности сохранить изменения при незаполненных полях личной почты и личного номера.

Шаг 1:
Авторизоваться https://csn.sytes.net/login

Шаг 2:
Нажать в хедере редактирование профиля

Шаг 3: 
Заполнить обязательные поля ФИО, должность, корп. почта и корп. телефон и сохранить

Ожидаемый результат:
Редактируемые данные сохраняются

Фактический результат:
Без заполнения необязательных полей Личная почта и Личный номер, данные не сохраняются

Окружение: https://csn.sytes.net Chrome Версия 113.0.5672.126

![Image](https://user-images.githubusercontent.com/134094409/252328239-85cd7555-bcd3-4472-8a1a-e09848a88a20.png)
![Image](https://user-images.githubusercontent.com/134094409/252328238-b73aff79-c400-4d13-a815-42f5f0a408b7.png)

**Comment by borrrv** [comment]
Сделано

**Comment by Oksaction** [comment]
Эти ошибки на странице Редактирование профиля появляются также в следующих случаях:
1. Создали нового пользователя, в браузере заполняем все обязательные поля ввода (соответственно кроме Личная почта и Личный телефон). Данные не сохраняются, возникает ошибка.
2. Создали нового пользователя, с помощью Postman заполняем все обязательные поля ввода (соответственно кроме Личная почта и Личный телефон). В браузере пробуем установить фото/предложенный аватар,  они не сохраняются, возникает ошибка.
3. Создали нового пользователя, в браузере заполняем все поля ввода. Далее пробуем удалить/заменить данные в полях Личная почта и Личный телефон. Данные не сохраняются, возникает ошибка.
